#!/bin/bash

# Version 0.1 without wakeup

machines="envelop encumber enroll"

maindir="Francesco/reSolve"
infile="input/NNLO_test_kvegas_parallel.dat"

rm *.txt

for iter in {1..100} ; do

echo "Iteration $iter"

# Machines loop
  PIDS=""
  for pc in $machines ; do
    echo $pc
# Cores loop
    for ii in {1..4} ; do
      echo $ii
      nohup ssh $pc "cd ${maindir}; ./resu.out ${infile} ${pc:0:5}_$ii" > no_${pc:0:5}_$ii.txt 2>/dev/null &
      PIDS="$PIDS $!"
    done

  done

  wait $PIDS

  echo "Ending iteration"

  nohup ./resu.out ${infile} END_ITER > no_final_$iter.txt 2>/dev/null &
  LASTPID=$!
  wait $LASTPID

  echo "Iteration over"
  echo

done

echo "That should be it"

exit
