#!/bin/bash

# Multi-machine parallel launcher - via ssh - for reSolve using k_vegas
version=0.2.2

##### HARDCODED INPUTS #####
machines="endear encumber"
max_iter=10
max_cores=4
exedir="$PWD"
EXE="./reSolve.out"
##### END HARDCODED INPUTS #####
echo
echo "#########################################################################"
echo "Multi-machine parallel launcher for reSolve + k_vegas -- version $version"
echo "Execution can be regulated by several parameter -- edit the script to see"
echo "#########################################################################"
echo

if [ $# -eq 0 ] ; then
  echo "Usage: $0 INPUT FILE (with full path)"
  exit
fi
infile=$1
if [ $# -gt 1 ] ; then
  echo
  echo "WARNING - the script only accepts one command argument, a reSolve input file. Parameters beyond the first are being ignored."
  echo
fi

echo "###########################################################"
echo "TAKE CARE: the \"machines\" string  MUST be edited by hand!"
echo "Current value of string:  $machines"
echo "###########################################################"
echo

echo "Requested iterations: $max_iter"
echo
iter=1
while [ $iter -le $max_iter ] ; do

echo "Iteration $iter"

# Machines loop
  PIDS=""
  for pc in $machines ; do
    loc_cores=`ssh $pc nproc --all 2>/dev/null`
    cores=$(( loc_cores > max_cores ? max_cores : loc_cores ))
    echo "Launching process in $pc on $cores cores"
# Cores loop
    ii=1
    while [ $ii -le $cores ] ; do
#      echo $ii
      tag=${pc:0:10}_$ii
#      echo $tag
      nohup ssh $pc "cd ${exedir}; $EXE ${infile} $tag" >nohup_${tag}_${iter}.out 2>/dev/null &
      PIDS="$PIDS $!"
      ii=$(( ii+1 ))
    done
    last_node=$pc
  done

  echo "Waiting for child processes..."
  wait $PIDS

# ITERATION END
  echo "Finalising iteration"
  nohup ssh ${last_node} "cd ${exedir}; $EXE ${infile} END_ITER" >nohup_iter_${iter}.out 2>/dev/null &
  LASTPID=$!
  wait $LASTPID
#
  iter=$(( iter+1 ))
  echo "Iteration over"
  echo

done

echo "That should be it"

exit
